version: '3.7'

services:
    server:
        image: dunglas/mercure:v0.8.0
        environment:
            ALLOW_ANONYMOUS: 1
            CORS_ALLOWED_ORIGINS: 'https://sto.automagistre.ru'
            JWT_KEY: aVerySecretKey
        networks:
            mercure:
                aliases:
                    - mercure.automagistre.ru
            ingress: {}
        deploy:
            labels:
                - "traefik.docker.network=proxy"
                - "traefik.enable=true"
                - "traefik.frontend.rule=Host:mercure.automagistre.ru"
                - "traefik.port=80"
                - "traefik.protocol=http"
                - "traefik.backend.loadbalancer.method=drr"

networks:
    ingress:
        external: true
        name: proxy
    mercure:
        driver: overlay
        name: mercure
